# Generated by Django 5.1.3 on 2024-11-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
